CREATE USER EC_STRUTS_GENERAL IDENTIFIED BY "atelier";

GRANT UNLIMITED TABLESPACE TO EC_STRUTS_GENERAL;

GRANT CREATE SESSION TO EC_STRUTS_GENERAL;

CREATE TABLE "EC_STRUTS_GENERAL"."COMPANY_MASTER" 
   ("COMPANY_CD" CHAR(10 BYTE) NOT NULL ENABLE, 
	"COMPANY_NAME" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
	"UNAVAILABLE_FLG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"UNAVAILABLE_REASON" VARCHAR2(150 BYTE), 
	"UNAVAILABLE_DATE" DATE, 
	"ZIP_NO1" VARCHAR2(3 BYTE), 
	"ZIP_NO2" VARCHAR2(4 BYTE), 
	"BUILDING" VARCHAR2(150 BYTE), 
	"ADDRESS" VARCHAR2(150 BYTE), 
	"TEL" VARCHAR2(12 BYTE), 	
	"MANICIPALIT" VARCHAR2(100 BYTE),
	"PREFECTURE_CD" CHAR(2 BYTE),
	"PRESIDENT_NAME" VARCHAR2(30 BYTE), 
	"CREDIT_LIMIT" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE, 
	"SALES_FLG" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"PHARCHASE_FLG" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"DELETE_FLG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATE_USER_ID" NUMBER(4,0) NOT NULL ENABLE, 
	"CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATE_USER_ID" NUMBER(4,0) NOT NULL ENABLE, 
	"UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATE_COUNT" NUMBER(5,0) NOT NULL ENABLE
   );

COMMENT ON COLUMN "EC_STRUTS_GENERAL"."COMPANY_MASTER"."COMPANY_CD" IS '会社コード';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."COMPANY_MASTER"."COMPANY_NAME" IS '会社名';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."COMPANY_MASTER"."UNAVAILABLE_FLG" IS '利用不可フラグ';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."COMPANY_MASTER"."UNAVAILABLE_REASON" IS '利用不可理由';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."COMPANY_MASTER"."UNAVAILABLE_DATE" IS '利用不可日付';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."COMPANY_MASTER"."ZIP_NO1" IS '郵便番号1';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."COMPANY_MASTER"."ZIP_NO2" IS '郵便番号2';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."COMPANY_MASTER"."PREFECTURE_CD" IS '都道府県No';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."COMPANY_MASTER"."MANICIPALIT" IS '市区町村';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."COMPANY_MASTER"."BUILDING" IS '建物';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."COMPANY_MASTER"."ADDRESS" IS '住所';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."COMPANY_MASTER"."TEL" IS '電話番号';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."COMPANY_MASTER"."PRESIDENT_NAME" IS '代表者名';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."COMPANY_MASTER"."CREDIT_LIMIT" IS '与信限度額';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."COMPANY_MASTER"."SALES_FLG" IS '売上可否フラグ';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."COMPANY_MASTER"."PHARCHASE_FLG" IS '購入可否フラグ';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."COMPANY_MASTER"."DELETE_FLG" IS '削除フラグ';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."COMPANY_MASTER"."CREATE_USER_ID" IS '作成者';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."COMPANY_MASTER"."CREATE_DATE" IS '新規作成日時';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."COMPANY_MASTER"."UPDATE_USER_ID" IS '最終記入者';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."COMPANY_MASTER"."UPDATE_DATE" IS '最終記入日時';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."COMPANY_MASTER"."UPDATE_COUNT" IS '更新回数';

CREATE TABLE "EC_STRUTS_GENERAL"."PREFECTURE_MASTER" 
   ("PREFECTURE_CD" CHAR(2) NOT NULL ENABLE, 
	"PREFECTURE_NAME" VARCHAR2(10) NOT NULL ENABLE, 
	"PREFECTURE_KANA" VARCHAR2(30) NOT NULL ENABLE, 
	"CREATE_USER_ID" NUMBER(4,0) NOT NULL ENABLE, 
	"CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATE_USER_ID" NUMBER(4,0) NOT NULL ENABLE, 
	"UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATE_COUNT" NUMBER(5,0) NOT NULL ENABLE
   );

COMMENT ON COLUMN "EC_STRUTS_GENERAL"."PREFECTURE_MASTER"."PREFECTURE_CD" IS '都道府県コード';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."PREFECTURE_MASTER"."PREFECTURE_NAME" IS '都道府県名';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."PREFECTURE_MASTER"."PREFECTURE_KANA" IS 'フリガナ';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."PREFECTURE_MASTER"."CREATE_USER_ID" IS '作成者';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."PREFECTURE_MASTER"."CREATE_DATE" IS '新規作成日時';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."PREFECTURE_MASTER"."UPDATE_USER_ID" IS '最終記入者';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."PREFECTURE_MASTER"."UPDATE_DATE" IS '最終記入日時';
COMMENT ON COLUMN "EC_STRUTS_GENERAL"."PREFECTURE_MASTER"."UPDATE_COUNT" IS '更新回数';

CREATE TABLE "EC_STRUTS_GENERAL"."JSP_CHAPTER7" 
   (	"KEY_CD" VARCHAR2(5) NOT NULL ENABLE, 
	"CONDITION1" VARCHAR2(10) NOT NULL ENABLE, 
	"CONDITION2" NUMBER(1,0) NOT NULL ENABLE, 
	"CREATE_USER_ID" VARCHAR2(4) NOT NULL ENABLE, 
	"CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATE_USER_ID" VARCHAR2(4) NOT NULL ENABLE, 
	"UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATE_COUNT" NUMBER(5,0) NOT NULL ENABLE
	);

COMMENT ON COLUMN JSP_CHAPTER7.KEY_CD IS 'キーコード';
COMMENT ON COLUMN JSP_CHAPTER7.CONDITION1 IS '検索項目1';
COMMENT ON COLUMN JSP_CHAPTER7.CONDITION2 IS '検索項目2';
COMMENT ON COLUMN JSP_CHAPTER7.CREATE_USER_ID IS '作成者';
COMMENT ON COLUMN JSP_CHAPTER7.CREATE_DATE IS '新規作成日時';
COMMENT ON COLUMN JSP_CHAPTER7.UPDATE_USER_ID IS '最終記入者';
COMMENT ON COLUMN JSP_CHAPTER7.UPDATE_DATE IS '最終記入日時';
COMMENT ON COLUMN JSP_CHAPTER7.UPDATE_COUNT IS '更新回数';

ALTER TABLE JSP_CHAPTER7 ADD CONSTRAINT JSP_CHAPTER7_KEY PRIMARY KEY (KEY_CD);